spring:
  application:
    name: neomentora

  datasource:
    url: jdbc:mysql://localhost:3306/neomentora?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    sql:
      init:
        mode: never

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /neomentora
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always
    include-binding-errors: always
