version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: neomentora
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
